### ISSUE TITLE
Unknown Color Format error, continuous loop

### ISSUE THREAD

**Issue by rcheung9** [olton/Metro-UI-CSS#1042]
This error loops infinitely and ends up crashing the browser.

Unknown color format! Error: Unknown color format!
    at Object.toRGB (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:15230)
    at Object.isDark (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:17464)
    at Object.isLight (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:17546)
    at Object._createStructure (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:208981)
    at Object._create (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:208439)
    at Object.init (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:208032)
    at HTMLUListElement.<anonymous> (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:5536)
    at Function.each (http://localhost:55734/Scripts/jquery-3.3.1.js:354:19)
    at jQuery.fn.init.each (http://localhost:55734/Scripts/jquery-3.3.1.js:189:17)
    at jQuery.fn.init.t.fn.(anonymous function) [as tabs] (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:5489)

**Comment by olton** [comment]
I have to guess which code leads to errors?

**Comment by olton** [comment]
Before create issue:

check for existing issues
create pen on codepen.io with your problem
describe the problem in detail

**Comment by rcheung9** [comment]
The tabs plugin fails on initialization.

**Comment by olton** [comment]
Clear cache

**Comment by olton** [comment]
please, if you want to receive answers, follow the three simple requirements for posing the problem
