### ISSUE TITLE
Bug with List and IE 11

### ISSUE THREAD

**Issue by arjarn** [olton/Metro-UI-CSS#1155]
Hi,

in my site, I'm using List component and having bug if I'm using IE11 (v11.492).
I think I made mistake (as often) but it's same bug with your documentation page : https://metroui.org.ua/list.html

There's error message (null reference) :

Metro 4 Components Library - v4.2.15.692 
Impossible d’obtenir la propriété  « dataset » d’une référence null ou non définie TypeError: Impossible d’obtenir la propriété  « dataset » d’une référence null ou non définie
   at fe._getItemContent (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:172092)
   at Anonymous function (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:172854)
   at fe.sorting (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:172689)
   at fe._createStructure (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:167916)
   at fe._build (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:164962)
   at fe._create (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:164827)
   at fe.init (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:162900)
   at Anonymous function (https://cdn.metroui.org.ua/v4/js/metro.min.js:7:5841)
   at each (https://code.jquery.com/jquery-3.2.1.min.js:2:2710)
   at r.prototype.each (https://code.jquery.com/jquery-3.2.1.min.js:2:994)

Thanx.

**Comment by olton** [comment]
Thank you. I fix it in 4.2.16. Wait for release or use develop branch https://github.com/olton/Metro-UI-CSS/tree/4.2.16
