### ISSUE TITLE
Form Validator inside dialog

### ISSUE THREAD

**Issue by formae98** [olton/Metro-UI-CSS#941]
Is there a way to avoid that the form validation closes the dialog form?
(perhaps i'm doing something wrong....)

Fabio

**Comment by olton** [comment]
Hi Fabio!

https://codepen.io/olton/pen/VWzQMq

**Comment by formae98** [comment]
It does not resolve the problem cause the submit button (even in the present of errors) calls a page refresh that closes the dialog

**Comment by olton** [comment]
Please create pen with your problem

**Comment by formae98** [comment]
Here is a single page with opened dialog.
If you press the "ADD" button (on the dialog) you can see that the html pages it's refreshed.

[accounts_form.zip](https://github.com/olton/Metro-UI-CSS/files/1105066/accounts_form.zip)

**Comment by formae98** [comment]
Any news?

**Comment by olton** [comment]
I do not quite understand what's going to happen

**Comment by formae98** [comment]
Do you need a simpler example?
(if i use the form validator without the modal, everything works without problem)

**Comment by olton** [comment]
add action="javascript:void(0)" and onsubmit="your_submit_control_function"

**Comment by formae98** [comment]
Thanks,
data validation works now but....
in case of error, the "submit button" is automatically disabled (why?)

**Comment by formae98** [comment]
metro.js:9824 Uncaught TypeError: that.funcs[func_name.trim(...)] is not a function
    at String.<anonymous> (http://localhost:8080/js/metro.js:9824:59)
    at Function.each (http://localhost:8080/js/jquery-2.1.3.min.js:2:2882)
    at HTMLInputElement.<anonymous> (http://localhost:8080/js/metro.js:9821:15)
    at Function.each (http://localhost:8080/js/jquery-2.1.3.min.js:2:2882)
    at $.(anonymous function).(anonymous function)._submit (http://localhost:8080/js/metro.js:9805:11)
    at $.(anonymous function).(anonymous function)._submit (http://localhost:8080/js/metro.js:519:37)
    at HTMLFormElement.element.(anonymous function).onsubmit (http://localhost:8080/js/metro.js:9786:25)

**Comment by formae98** [comment]
I have the same error in the file i sended you too...
